=head1 NAME

TPMLIB_RecreateSvnBaseSecret  - Recreate a TPM 2's SVN-limited hierarchy base secret

=head1 LIBRARY

TPM library (libtpms, -ltpms)

=head1 SYNOPSIS

B<#include <libtpms/tpm_types.h>>

B<#include <libtpms/tpm_library.h>>

B<#include <libtpms/tpm_error.h>>

B<TPM_RESULT TPMLIB_RecreateSvnBaseSecret(void);>

=head1 DESCRIPTION

B<TPMLIB_RecreateSvnBaseSecret()> is used to recreate the internal base SVN
secret that is used for by the SVN-limited hierachy to derive its secret
from by adding the 16bit SVN number to it. Since the SVN base secret is part
of the permanent/persistent state of a TPM 2, this function should be called
after loading the state or before processing the first command. This can for
example be done right after I<TPMLIB_MainInit()> or as late as just before
I<TPMLIB_Process()>.

The side effect of recreating the base SVN secret is that previous firmware
SVN secrets cannot be created anymore and objects (keys) associated with the
SVN-limited hierachy cannot be used anymore.

=head1 SEE ALSO

B<TPMLIB_MainInit>, B<TPMLIB_Process>(3)

=cut
