include(CheckFunctionExists)

function(check_openssl_functions OPENSSL_FUNCTION_TYPE SYMBOL_LIST)
    set(IS_THERE BOOL 1)
    foreach(CRYPTO_FUNC IN LISTS SYMBOL_LIST)
        set(CMAKE_REQUIRED_LIBRARIES crypto)
        check_function_exists(${CRYPTO_FUNC} IS_THERE)
        message(STATUS ${CRYPTO_FUNC})
        if(NOT IS_THERE)
            message(STATUS "Not Found ${CRYPTO_FUNC}")
            break()
        else()
            message(STATUS "Exists ${CRYPTO_FUNC}")
        endif()
    endforeach()
    set(${OPENSSL_FUNCTION_TYPE} ${IS_THERE} PARENT_SCOPE)
endfunction()
